### ISSUE TITLE
想让大佬帮我解决一下安卓手机上，怎么设置同文拼音输入法。

### ISSUE THREAD

**Issue by pros2021** [WhiredPlanck/trime-new#3]
大佬你的qq号多少，或者其他通讯帐号也行。我需要实时咨询：到底怎么设置拼音输入。
文档写的什么东风破，也看不懂是什么玩意。

全网也找不到有解说的视频教程，希望能加大佬你的好友，赶紧解决这个历史遗留的烂摊子。

**Comment by asgsdbrseg** [comment]
你好，同文暂不支持拼音。更多详情请加QQ群了解：224230445，在完成人机识别后即可成功入群。
